#include "repl.h"

void ColtRun(const char* byte_code_out, StringView to_parse)
{
	AST ast;
	ASTInit(&ast);
	ColtScanOptions options;
	//Choose default options
	memset(&options, 0, sizeof(ColtScanOptions));

	if (ASTParse(&ast, to_parse, &options))
	{
		Chunk chunk;
		ChunkInit(&chunk);
		if (generateByteCode(&chunk, &ast.table, &ast.expr, false))
		{
			if (byte_code_out != NULL)
				ChunkSerialize(&chunk, byte_code_out);
			StackVM vm;
			StackVMInit(&vm);
			if (StackVMRun(&vm, &chunk) == 0)
				fputc('\n', stdout);
			else
				fputs(CONSOLE_FOREGROUND_BRIGHT_RED"\nError: "CONSOLE_COLOR_RESET "VM did not run successfully!\n", stdout);
			StackVMFree(&vm);
		}
		ChunkFree(&chunk);
	}
	ASTFree(&ast);
}

void ColtREPL(const char* byte_code_out)
{
	AST ast;
	ASTInit(&ast);
	ColtScanOptions options;
	//Choose default options
	memset(&options, 0, sizeof(ColtScanOptions));
	//But we do not want to warn for unused result of expressions like '20 + 10'
	options.no_warn_unused_result = true;

	while (!feof(stdin))
	{
		fputs(CONSOLE_FOREGROUND_BRIGHT_GREEN "> " CONSOLE_COLOR_RESET, stdout);
		String line = StringREPLGetLine();
		if (line.size != 1) //if string not empty
		{
			//append ';' if line does not end with one
			if (line.ptr[line.size - 2] != ';')
				StringAppendChar(&line, ';');
			repl_run(&ast, StringToStringViewWithNUL(&line), &options, byte_code_out);
		}
		StringFree(&line);
	}
	ASTFree(&ast);
}

void repl_run(AST* ast, StringView strv, const ColtScanOptions* options, const char* byte_code_out)
{
	if (ASTParse(ast, strv, options))
	{
		Chunk chunk;
		ChunkInit(&chunk);

		if (generateByteCode(&chunk, &ast->table, &ast->expr, true))
		{
			if (byte_code_out != NULL)
				ChunkSerialize(&chunk, byte_code_out);
			ChunkDisassemble(&chunk, "GENERATED BYTE-CODE");
			StackVM vm;
			StackVMInit(&vm);
			if (StackVMRun(&vm, &chunk) == 0)
			{
				fputc('\n', stdout);
				//if we run successfully, we update the globals
				repl_write_global(&ast->table.glob_table, &chunk);
			}
			else
				fputs(CONSOLE_FOREGROUND_BRIGHT_RED"\nError: "CONSOLE_COLOR_RESET "VM did not run successfully!\n", stdout);
			StackVMFree(&vm);
		}
		ChunkFree(&chunk);
	}
}

void repl_write_global(GlobalTable* table, Chunk* chunk)
{
	if (table->count == 0)
		return;

	const QWORD* global_offset = (QWORD*)(chunk->code + ChunkGetGLOBALSection(chunk));
	for (size_t i = 0; i < table->capacity; i++)
	{
		if (table->entries[i].key.ptr == NULL)
			continue;
		//write the updated value
		table->entries[i].value = *(global_offset + table->entries[i].counter_nb);
	}
}