#ifndef HG_COLT_REPL
#define HG_COLT_REPL

#include "precomph.h"

/// @brief Read Evaluate Print Loop of Colt
/// @param byte_code_out The path to serialize generated byte-code
void ColtREPL(const char* byte_code_out);

/// @brief Runs code and serializes it if 'byte_code_out' is not NULL
/// @param ast The initialized AST to use to parse the code
/// @param strv The StringView over the code to run
/// @param byte_code_out The file path to where to serialize the generated byte-code
void repl_run(AST* ast, StringView strv, const char* byte_code_out);

/// @brief Updates the value of active entries of a VariableTable from a Chunk
/// @param table The table whose entries to update
/// @param chunk The Chunk from which to read the updated values
void repl_write_global(VariableTable* table, Chunk* chunk);

#endif //HG_COLT_REPL