#include "repl.h"

void ColtREPL(const char* byte_code_out)
{
	AST ast;
	ASTInit(&ast);
	while (!feof(stdin))
	{
		fputs(CONSOLE_FOREGROUND_BRIGHT_GREEN "> " CONSOLE_COLOR_RESET, stdout);
		String line = StringGetLine();
		repl_run(&ast, StringToStringViewWithNUL(&line), byte_code_out);
		StringFree(&line);
	}
	ASTFree(&ast);
}

void repl_run(AST* ast, StringView strv, const char* byte_code_out)
{
	if (ASTParse(ast, strv))
	{
		Chunk chunk;
		ChunkInit(&chunk);

		if (generateByteCode(&chunk, &ast->var_table, ast->expr))
		{
			if (byte_code_out != NULL)
				ChunkSerialize(&chunk, byte_code_out);
			StackVM vm;
			StackVMInit(&vm);
			if (StackVMRun(&vm, &chunk) == 0)
				fputc('\n', stdout);
			StackVMFree(&vm);
			repl_write_global(&ast->var_table, &chunk);
		}
		ChunkFree(&chunk);
	}
}

void repl_write_global(VariableTable* table, Chunk* chunk)
{
	if (table->count == 0)
		return;
	size_t offset = 0;
	QWORD* global_offset = (QWORD*)(chunk->code + *(uint64_t*)(chunk->code));
	for (size_t i = 0; i < table->capacity; i++)
	{
		if (table->entries[i].key.ptr == NULL)
			continue;
		//write the updated value
		table->entries[i].value = *(global_offset + offset++);
	}
}

#if 0

if (view.end - view.start > 1)
	{
		if (ASTParse(ast, view))
		{
			printf(CONSOLE_FOREGROUND_BRIGHT_GREEN"Successfully created an AST!\n"
				"Type of expression: %.*s!\n"CONSOLE_COLOR_RESET, (uint32_t)(ast->expr->expr_type.name.end - ast->expr->expr_type.name.start),
				ast->expr->expr_type.name.start);

			fputs(CONSOLE_FOREGROUND_BRIGHT_BLUE"Generating byte-code...\n"CONSOLE_COLOR_RESET, stdout);
			
			Chunk chunk;
			ChunkInit(&chunk);

			if (generateByteCode(&chunk, &ast->var_table, ast->expr))
			{
				if (byte_out != NULL)
					ChunkSerialize(&chunk, byte_out);
				ChunkDisassemble(&chunk, "GENERATED BYTE-CODE");
				StackVM vm;
				StackVMInit(&vm);
				if (StackVMRun(&vm, &chunk) == 0)
					fputs(CONSOLE_FOREGROUND_BRIGHT_GREEN"\nSuccessfully run VM!\n"CONSOLE_COLOR_RESET, stdout);
				else
					fputs(CONSOLE_FOREGROUND_BRIGHT_RED"\nVM did not run successfully!\n"CONSOLE_COLOR_RESET, stdout);
				StackVMFree(&vm);
			}
			else
			{
				print_error_string("Couldn't generate byte-code...");
			}

			ChunkFree(&chunk);
		}
	}
}

#endif