#include "repl.h"

void ColtREPL(const char* byte_code_out)
{
	AST ast;
	ASTInit(&ast);
	while (!feof(stdin))
	{
		fputs(CONSOLE_FOREGROUND_BRIGHT_GREEN "> " CONSOLE_COLOR_RESET, stdout);
		String line = StringGetLine();
		if (line.size != 1) //if string not empty
		{
			//append ';' if line does not end with one
			if (line.ptr[line.size - 2] != ';')
				StringAppendChar(&line, ';');
			repl_run(&ast, StringToStringViewWithNUL(&line), byte_code_out);
		}
		StringFree(&line);
	}
	ASTFree(&ast);
}

void repl_run(AST* ast, StringView strv, const char* byte_code_out)
{
	if (ASTParse(ast, strv))
	{
		Chunk chunk;
		ChunkInit(&chunk);

		if (generateByteCode(&chunk, &ast->table, ast->expr))
		{
			if (byte_code_out != NULL)
				ChunkSerialize(&chunk, byte_code_out);
			ChunkDisassemble(&chunk, "GENERATED BYTE-CODE");
			StackVM vm;
			StackVMInit(&vm);
			if (StackVMRun(&vm, &chunk) == 0)
				fputc('\n', stdout);
			StackVMFree(&vm);
			repl_write_global(&ast->table.var_table, &chunk);
		}
		ChunkFree(&chunk);
	}
}

void repl_write_global(VariableTable* table, Chunk* chunk)
{
	if (table->count == 0)
		return;
	size_t offset = 0;
	const QWORD* global_offset = (QWORD*)(chunk->code + ChunkGetGLOBALSection(chunk));
	for (size_t i = 0; i < table->capacity; i++)
	{
		if (table->entries[i].key.ptr == NULL)
			continue;
		//write the updated value
		table->entries[i].value = *(global_offset + offset++);
	}
}