#ifndef HG_COLT_REPL
#define HG_COLT_REPL

#include "precomph.h"

/// @brief Compiles 'to_parse' to byte-code and runs it
/// @param byte_code_out Path to the file where to serialize the generated byte-code or NULL
/// @param to_parse The StringView containing a NUL terminator to compile
void ColtRun(const char* byte_code_out, StringView to_parse);

/// @brief Read Evaluate Print Loop of Colt
/// @param byte_code_out The path to serialize generated byte-code
void ColtREPL(const char* byte_code_out);

/// @brief Runs code and serializes it if 'byte_code_out' is not NULL
/// @param ast The initialized AST to use to parse the code
/// @param strv The StringView over the code to run
/// @param options The options used for scanning
/// @param flags The flags used for byte-code generation
/// @param byte_code_out The file path to where to serialize the generated byte-code
void repl_run(AST* ast, StringView strv, const ColtScanOptions* options, const ByteCodeGeneratorFlags* flags, const char* byte_code_out);

/// @brief Updates the value of active entries of a GlobalTable from a Chunk
/// @param table The table whose entries to update
/// @param chunk The Chunk from which to read the updated values
void repl_write_global(GlobalTable* table, Chunk* chunk);

#endif //HG_COLT_REPL