#include "precomph.h"

void debug_ast(AST* ast, StringView view, const char* byte_out)
{
	if (view.end - view.start > 1)
	{
		if (ASTParse(ast, view))
		{
			printf(CONSOLE_FOREGROUND_BRIGHT_GREEN"Successfully created an AST!\n"
				"Type of expression: %.*s!\n"CONSOLE_COLOR_RESET, (uint32_t)(ast->expr->expr_type.name.end - ast->expr->expr_type.name.start),
				ast->expr->expr_type.name.start);

			fputs(CONSOLE_FOREGROUND_BRIGHT_BLUE"Generating byte-code...\n"CONSOLE_COLOR_RESET, stdout);
			
			Chunk chunk;
			ChunkInit(&chunk);

			if (generateByteCode(&chunk, &ast->var_table, ast->expr))
			{
				if (byte_out != NULL)
					ChunkSerialize(&chunk, byte_out);
				ChunkDisassemble(&chunk, "GENERATED BYTE-CODE");
				StackVM vm;
				StackVMInit(&vm);
				if (StackVMRun(&vm, &chunk) == 0)
					fputs(CONSOLE_FOREGROUND_BRIGHT_GREEN"\nSuccessfully run VM!\n"CONSOLE_COLOR_RESET, stdout);
				else
					fputs(CONSOLE_FOREGROUND_BRIGHT_RED"\nVM did not run successfully!\n"CONSOLE_COLOR_RESET, stdout);
				StackVMFree(&vm);
			}
			else
			{
				print_error_string("Couldn't generate byte-code...");
			}

			ChunkFree(&chunk);
		}
		else
		{
			print_error_string("Couldn't create valid AST!");
		}
	}
}

int main(int argc, const char** argv)
{
	ParseResult args = ParseArguments(argc, argv);
	if (args.file_path_in == NULL)
	{
		AST ast;
		ASTInit(&ast);		
		while (!feof(stdin))
		{
			fputs(CONSOLE_FOREGROUND_BRIGHT_MAGENTA"> "CONSOLE_COLOR_RESET, stdout);
			String line = StringGetLine();
			debug_ast(&ast, StringToStringViewWithNUL(&line), args.byte_code_out);
			StringFree(&line);
		}
		ASTFree(&ast);
	}
	else
	{
		AST ast;
		ASTInit(&ast);
		String file_content = StringGetFileContent(args.file_path_in);
		debug_ast(&ast, StringToStringViewWithNUL(&file_content), args.byte_code_out);
		StringFree(&file_content);
		ASTFree(&ast);
	}
	DUMP_MEMORY_LEAKS();
}