#include "precomph.h"
#include "vm/repl.h"

void ColtRun(ParseResult args, StringView to_parse)
{
	AST ast;
	ASTInit(&ast);
	ColtScanOptions options;
	//Choose default options
	memset(&options, 0, sizeof(ColtScanOptions));

	if (ASTParse(&ast, to_parse, &options))
	{
		Chunk chunk;
		ChunkInit(&chunk);
		if (generateByteCode(&chunk, &ast.table, &ast.expr, false))
		{
			if (args.byte_code_out != NULL)
				ChunkSerialize(&chunk, args.byte_code_out);
			ChunkDisassemble(&chunk, args.file_path_in == NULL ? "GENERATED BYTE-CODE" : args.file_path_in);
			StackVM vm;
			StackVMInit(&vm);
			if (StackVMRun(&vm, &chunk) == 0)
				fputc('\n', stdout);
			else
				fputs(CONSOLE_FOREGROUND_BRIGHT_RED"\nError: "CONSOLE_COLOR_RESET "VM did not run successfully!\n", stdout);
			StackVMFree(&vm);
		}
		ChunkFree(&chunk);
	}
	ASTFree(&ast);
}

int main(int argc, const char** argv)
{
	ParseResult args = ParseArguments(argc, argv);
	if (args.file_path_in == NULL)
	{
		ColtREPL(args.byte_code_out);
	}
	else
	{
		String file_content = StringGetFileContent(args.file_path_in);
		//Parses and run if valid.
		ColtRun(args, StringToStringViewWithNUL(&file_content));
		StringFree(&file_content);
	}
	DUMP_MEMORY_LEAKS();
}